### ISSUE TITLE
Finish keypoints

### ISSUE THREAD

**Issue by una-dinosauria** [una-dinosauria/image-annotator#1]
I created a data structure that includes almost all the datapoints (paws, head and tail). We are missing the body center and the middle of the tail. Ideally we would also color the lines as to make them distinctive and (possibly) pretty.

Here is a nice website to inspire color selection: http://colorbrewer2.org/

**Comment by umgupta** [comment]
I am creating a variable that will have all the data we need to store or save. This has an added advantage that when we want to save the info we can just dump it as a json.

**Comment by una-dinosauria** [comment]
Yes! Definitely jsonifying will be necessary when we send this to the
server side. Thanks!

On Tue, Feb 10, 2015 at 10:12 AM, Umang Gupta notifications@github.com
wrote:

> I am creating a variable that will have all the data we need to store or
> save. This has an added advantage that when we want to save the info we can
> just dump it as a json.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jltmtz/image-annotator/issues/1#issuecomment-73751496
> .

## 

Julieta

**Comment by umgupta** [comment]
I think this is done.
