### ISSUE TITLE
Images not loading 

### ISSUE THREAD

**Issue by umgupta** [una-dinosauria/image-annotator#5]
see https://github.com/jltmtz/image-annotator/commit/2a8129b0d1e5467ab2b951777eafb5ec5ed5df11

**Comment by una-dinosauria** [comment]
Yeah, I still see them loading intermittently, or kind of crop when I generate the random puppet.
![selection_260](https://cloud.githubusercontent.com/assets/3733964/6173924/6032d68a-b2a0-11e4-8364-f1bd7110c677.png)
I'll look into it over the weekend!

**Comment by umgupta** [comment]
Just a note.. refreshing the page works everytime. Seems like all data is not loaded only when you open the page first time.
