### ISSUE TITLE
Displacement due to optical flow

### ISSUE THREAD

**Issue by Jigyasu** [una-dinosauria/image-annotator#6]
When I extend annotations based on optical flow, the puppet does not seem to move in the direction of optical flow. 

I suspect there is a problem with adding displacement due to optical flow to the current position. For example in the current demo, between from 1-11, the person moves to the left but puppet moves up.

**Comment by umgupta** [comment]
Will be fixed in next commit. This was due to open-cv's way of writing in BGR format rather than RGB (which is the way browser loads it). It is taken care in canvas reading part in js
