### ISSUE TITLE
Interpolation does not work if I move the whole puppet

### ISSUE THREAD

**Issue by Jigyasu** [una-dinosauria/image-annotator#8]
Here is a scenario:
1. I use flow to transfer annotations from frame 1 to frame 5.
2. Now I adjusted the whole puppet using the marker at the center.
3. I find frames 1 to 4 are not interpolated based on the new location of the puppet in frame 5.

**Comment by umgupta** [comment]
It was intended to work that way. Anyways, I will add that. Changing label to enhancement

**Comment by umgupta** [comment]
Interpolation for the whole puppet added. Will be seen in next commit.
