### ISSUE TITLE
Delete behavior should interpolate frame 

### ISSUE THREAD

**Issue by Jigyasu** [una-dinosauria/image-annotator#9]
The delete behavior currently completely deletes the puppet from the frame. Here is how I think we should handle this:
1. If we try to delete an intermediate frame (a frame where both left and the right frames have annotation), it should:
   a) interpolate again all the frame (between the surrounding keyframes) to negate the effects of the deleted frame (just assume that there is no frame there).
   b) just replace the deleted frame by the interpolation of two neighboring frames. This situation arises when a user tries to adjust the frame too much and just wants to clear their changes.
   c) In short, delete == clear my changes, in this case.
2. If you delete a boundary frame (assuming that it is a keyframe):
   a) again, interpolate the affected frame near it assuming that the current frame does not exist.
   b) make the neighboring frame a keyframe.
   c) remove the annotation of the current frame.
3. It implies that if someone needs to delete the whole sequence, they need to start at one of the ends.

**Comment by umgupta** [comment]
This is done (in essence). However, there might be some cases when we are not able to delete the frame due to inconsistency in annotation data.
